name: Complete Quality Control
on:
    pull_request:
        paths:
            - backend/src/**
            - backend/pom.xml
            - frontend/src/**
            - frontend/angular.json
        branches: 
            - main
    workflow_dispatch:

jobs:

  build-backend:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Server compile
        run: mvn clean compile


  backend-unit-tests:
    runs-on: ubuntu-latest
    needs: build-backend
    defaults: 
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Run unit tests
        run: mvn test -Dgroups='unit'


  backend-integration-tests:
    runs-on: ubuntu-latest
    needs: backend-unit-tests
    defaults: 
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Run integration tests
        run: mvn test -Dgroups='integration'


  backend-e2e-tests:
    runs-on: ubuntu-latest
    needs: backend-integration-tests
    defaults: 
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Run system tests
        run: mvn test -Dgroups='e2e'


  build-frontend:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
      
      - name: Frontend compile
        run: npm run build
  

  frontend-unit-tests:
    runs-on: ubuntu-latest
    needs: build-frontend
    defaults: 
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit
      

  frontend-integration-tests:
    runs-on: ubuntu-latest
    needs: frontend-unit-tests
    defaults: 
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Start backend
        run:
            mvn spring-boot:run "-Dspring-boot.run.profiles=test" &
            until nc -z localhost 8080; do sleep 2; done
        working-directory: ./backend

      - name: Run integration tests
        run: npm run test:integration


  frontend-e2e-tests:
    runs-on: ubuntu-latest
    needs: frontend-integration-tests
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Serve Angular in background
        run: npm start &
        working-directory: ./frontend

      - name: Wait for Angular to be ready
        run: npx wait-on http://localhost:4200
        working-directory: ./frontend

      - name: Run system tests
        run: mvn -Dtest=UISystemTest test
        working-directory: ./backend